### ISSUE TITLE
Add a selection of currencies in the conversion window

### ISSUE THREAD

**Issue by DraganRatkovich** [mesteranas/CurrencyConverter-nvda-add-on#1]
Hi,

Currently, to select currencies, we need to use the settings panel and select the desired currency from the appropriate category.

@mesteranas It would be much better to add a currency selection combo box directly to the conversion window for easy selection and conversion between currencies, without having to open the settings panel every time.

Of course, this also requires feedback from users, whether they agree or not.

Overall, this is a really nice and useful addon, so thank you for your great work.

**Comment by mesteranas** [comment]
Ok my friend I'll add it in the next version

**Comment by DraganRatkovich** [comment]
Completed in 4158aaf
