### ISSUE TITLE
addon stopt working

### ISSUE THREAD

**Issue by Skier7** [mesteranas/CurrencyConverter-nvda-add-on#4]
hi
this addon stopt working randomly one day, i am able to select what currency to convert but when i enter on next my hole computer freezes, it should open the windo with the converted currency but my hole computer just freezes for a wile and i can't do anything, i am using nvda 2024.3.1 and windows 11 2023h2

**Comment by mesteranas** [comment]
Ok i will fix this problem fast
Thank you to remind me

**Comment by George-br** [comment]
yes, same problem

**Comment by mesteranas** [comment]
hello 
      i fixed the problem 
      you can download the new version from the link
      https://github.com/mesteranas/CurrencyConverter-nvda-add-on/releases/download/v2.0/currency_converter_2.0.nvda-addon
      or from the addon store
